-- MySQL Script generated by MySQL Workbench
-- Sun Nov  4 21:50:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jtm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jtm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jtm` ;
USE `jtm` ;

-- -----------------------------------------------------
-- Table `jtm`.`pub_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jtm`.`pub_user` (
  `id` INT(6) ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_name` VARCHAR(128) NOT NULL COMMENT '用户名称',
  `user_email` VARCHAR(128) NOT NULL COMMENT '电子邮箱',
  `password` VARCHAR(128) NOT NULL COMMENT '密码',
  `salt` VARCHAR(256) NOT NULL COMMENT '盐值',
  `state` VARCHAR(1) NOT NULL COMMENT '状态',
  `create_time` TIMESTAMP NULL,
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `invalid_time` TIMESTAMP NULL COMMENT '作废时间',
  `invalid_user` INT(6) NULL COMMENT '作废人员',
  `invalid_reason` TIMESTAMP NULL COMMENT '作废类型',
  `invalid_reason_desc` TIMESTAMP NULL COMMENT '作废原因描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
alter table `jtm`.`pub_user` AUTO_INCREMENT = 100000;


-- -----------------------------------------------------
-- Table `jtm`.`sys_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jtm`.`sys_permission` (
  `id` INT(6) ZEROFILL NOT NULL AUTO_INCREMENT,
  `available` VARCHAR(45) NULL COMMENT '是否锁定',
  `name` VARCHAR(45) NULL COMMENT '权限名称',
  `parent_id` VARCHAR(45) NULL COMMENT '父节点',
  `parent_ids` VARCHAR(45) NULL,
  `permission` VARCHAR(45) NULL COMMENT '权限编号',
  `resource_type` VARCHAR(45) NULL COMMENT '资源类型',
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
alter table `jtm`.`sys_permission` AUTO_INCREMENT = 100000;


-- -----------------------------------------------------
-- Table `jtm`.`sys_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jtm`.`sys_role` (
  `id` INT(6) ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '主键',
  `available` VARCHAR(128) NULL COMMENT '是否锁定',
  `description` VARCHAR(128) NULL COMMENT '说明',
  `role` VARCHAR(128) NULL COMMENT '权限',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
alter table `jtm`.`sys_role` AUTO_INCREMENT = 100000;


-- -----------------------------------------------------
-- Table `jtm`.`sys_role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jtm`.`sys_role_permission` (
  `id` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `sys_role_id` INT(6) ZEROFILL NOT NULL,
  `sys_permission_id` INT(6) ZEROFILL NOT NULL,
  PRIMARY KEY (`id`, `sys_role_id`, `sys_permission_id`),
  CONSTRAINT `fk_sys_role_permission_sys_role1`
    FOREIGN KEY (`sys_role_id`)
    REFERENCES `jtm`.`sys_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_role_permission_sys_permission1`
    FOREIGN KEY (`sys_permission_id`)
    REFERENCES `jtm`.`sys_permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
alter table `jtm`.`sys_role_permission` AUTO_INCREMENT = 100000;

-- -----------------------------------------------------
-- Table `jtm`.`sys_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jtm`.`sys_user_role` (
  `id` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `pub_user_id` INT(6) ZEROFILL NOT NULL,
  `sys_role_id` INT(6) ZEROFILL NOT NULL,
  PRIMARY KEY (`id`, `pub_user_id`, `sys_role_id`),
  CONSTRAINT `fk_sys_user_role_pub_user`
    FOREIGN KEY (`pub_user_id`)
    REFERENCES `jtm`.`pub_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_user_role_sys_role1`
    FOREIGN KEY (`sys_role_id`)
    REFERENCES `jtm`.`sys_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
alter table `jtm`.`sys_user_role` AUTO_INCREMENT = 100000;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE TABLE IF NOT EXISTS `jtm`.`pub_user_session` (
  `sid` INT(6) NULL COMMENT 'PK',
  `user_code` VARCHAR(45) NULL COMMENT '用户编码',
  `remote_ip` VARCHAR(45) NULL COMMENT 'remote_ip\n',
  `token` VARCHAR(64) NULL COMMENT 'token',
  `tstatus` VARCHAR(1) NULL COMMENT '状态',
  `out_time` TIMESTAMP NULL COMMENT '结束时间',
  `start_time` TIMESTAMP NULL COMMENT '开始时间')
ENGINE = InnoDB;